spring:
  profiles:
    include:
      - database
  jwt:
    secret: emVyby1iYXNlLXNwcmluZy1ib290LWRpdmlkZW5kLXR1dG9yaWFsLWp3dC1zZWNyZXQta2V5
    prefix: "Bearer "

scheduler:
  review:
    test_update: 0 * * * * *
    update: 0 0 0/1 * * *

server:
  port: 8080
